// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package generate_models

import (
	"time"
)

const TableNameEvent = "events"

// Event mapped from table <events>
type Event struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Idivc       int32     `gorm:"column:idivc" json:"idivc"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Description string    `gorm:"column:description" json:"description"`
	Datestart   time.Time `gorm:"column:datestart;not null" json:"datestart"`
	Dateend     time.Time `gorm:"column:dateend;not null" json:"dateend"`
	Typeoc      bool      `gorm:"column:typeoc" json:"typeoc"`
	Placeadress string    `gorm:"column:placeadress" json:"placeadress"`
	Usercreater int32     `gorm:"column:usercreater" json:"usercreater"`
	Typeevents  string    `gorm:"column:typeevents" json:"typeevents"`
}

// TableName Event's table name
func (*Event) TableName() string {
	return TableNameEvent
}
