// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package generate_models

const TableNameIvc = "ivc"

// Ivc mapped from table <ivc>
type Ivc struct {
	ID      int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name    string `gorm:"column:name;not null" json:"name"`
	Address string `gorm:"column:address" json:"address"`
}

// TableName Ivc's table name
func (*Ivc) TableName() string {
	return TableNameIvc
}
