// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package generate_models

const TableNameMediafile = "mediafiles"

// Mediafile mapped from table <mediafiles>
type Mediafile struct {
	ID   int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type int32 `gorm:"column:type" json:"type"`
}

// TableName Mediafile's table name
func (*Mediafile) TableName() string {
	return TableNameMediafile
}
