// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package generate_models

const TableNameMediafileforevent = "mediafileforevents"

// Mediafileforevent mapped from table <mediafileforevents>
type Mediafileforevent struct {
	ID       int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Idfile   int32 `gorm:"column:idfile" json:"idfile"`
	Idevents int32 `gorm:"column:idevents" json:"idevents"`
}

// TableName Mediafileforevent's table name
func (*Mediafileforevent) TableName() string {
	return TableNameMediafileforevent
}
