// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package generate_models

const TableNameSubtypeevent = "subtypeevents"

// Subtypeevent mapped from table <subtypeevents>
type Subtypeevent struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string `gorm:"column:name;not null" json:"name"`
	Idtypeevents int32  `gorm:"column:idtypeevents" json:"idtypeevents"`
}

// TableName Subtypeevent's table name
func (*Subtypeevent) TableName() string {
	return TableNameSubtypeevent
}
