// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package generate_models

const TableNameTypeevent = "typeevents"

// Typeevent mapped from table <typeevents>
type Typeevent struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName Typeevent's table name
func (*Typeevent) TableName() string {
	return TableNameTypeevent
}
