// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package generate_models

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID      int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Mail    string `gorm:"column:mail" json:"mail"`
	Name    string `gorm:"column:name" json:"name"`
	Isadmin bool   `gorm:"column:isadmin" json:"isadmin"`
	Idivc   int32  `gorm:"column:idivc" json:"idivc"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
