// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package generate_models

const TableNameUsersevent = "usersevents"

// Usersevent mapped from table <usersevents>
type Usersevent struct {
	ID               int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Iduser           int32  `gorm:"column:iduser" json:"iduser"`
	Idevents         int32  `gorm:"column:idevents" json:"idevents"`
	Attendance       string `gorm:"column:attendance;default:false" json:"attendance"`
	Notificationtime string `gorm:"column:notificationtime" json:"notificationtime"`
}

// TableName Usersevent's table name
func (*Usersevent) TableName() string {
	return TableNameUsersevent
}
