services:
  frontend:
    build:
      context: ./packages/frontend
    ports:
      - "3000:8081"
    depends_on:
      - backend

  backend:
    build:
      context: ./packages/backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=appdb
    depends_on:
      - db

  db:
    image: postgres:15 
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data 

volumes:
  pg_data: