DROP TABLE IF EXISTS usersEvents CASCADE;
DROP TABLE IF EXISTS mediaFileForEvents CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS ivcAdmins CASCADE;
DROP TABLE IF EXISTS ivc CASCADE;
DROP TABLE IF EXISTS mediaFiles CASCADE;
DROP TABLE IF EXISTS typeFiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;